// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAg2mAYksPJ5Tl_861T33lcsnFMwsJuV0',
    appId: '1:436497557471:web:78246783bbeb8dd666066a',
    messagingSenderId: '436497557471',
    projectId: 'enspd-link-app',
    authDomain: 'enspd-link-app.firebaseapp.com',
    storageBucket: 'enspd-link-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1VQ88SCqLgb8fZ-kRWDgw_5_MSo9ldlg',
    appId: '1:436497557471:android:c45452fa586560a566066a',
    messagingSenderId: '436497557471',
    projectId: 'enspd-link-app',
    storageBucket: 'enspd-link-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2DuwVImrTIQxhtWzVUBETebhzswMliU',
    appId: '1:436497557471:ios:b2170326996fac7366066a',
    messagingSenderId: '436497557471',
    projectId: 'enspd-link-app',
    storageBucket: 'enspd-link-app.firebasestorage.app',
    iosBundleId: 'com.example.enspdLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2DuwVImrTIQxhtWzVUBETebhzswMliU',
    appId: '1:436497557471:ios:b2170326996fac7366066a',
    messagingSenderId: '436497557471',
    projectId: 'enspd-link-app',
    storageBucket: 'enspd-link-app.firebasestorage.app',
    iosBundleId: 'com.example.enspdLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAg2mAYksPJ5Tl_861T33lcsnFMwsJuV0',
    appId: '1:436497557471:web:02fd6c5c56b7212466066a',
    messagingSenderId: '436497557471',
    projectId: 'enspd-link-app',
    authDomain: 'enspd-link-app.firebaseapp.com',
    storageBucket: 'enspd-link-app.firebasestorage.app',
  );
}
